version: "3"

services:
  backend:
    container_name: backend
    build: ./
    image: backend
    ports:
      - 3000:3000
    restart: on-failure:3
    networks:
      - 42mogle_network
    env_file:
      - .env
      - .env.api
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres:14.9-alpine3.18
    restart: on-failure:3
    networks:
      - 42mogle_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: "Asia/Seoul"
    env_file:
      - .env
    healthcheck:
      test: pg_isready -d $POSTGRES_DB -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER
      interval: 10s
      timeout: 30s
      retries: 20
      start_period: 10s

volumes:
  postgres_data:

networks:
  42mogle_network:
    driver: bridge