version: "3"

services:
  backend:
    container_name: backend
    build: ./
    image: backend
    ports:
      - 3000:3000
    restart: on-failure:3
    networks:
      - 42mogle_network
    env_file:
      - .env
      - .env.api
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:14.9-alpine3.18
    restart: on-failure:3
    networks:
      - 42mogle_network
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      TZ: "Asia/Seoul"
    env_file:
      - .env

networks:
  42mogle_network:
    driver: bridge
